import { Book } from "@/types/book";

/**
 * 더미 도서 데이터 — 나중에 실제 샘플 JSON으로 교체합니다.
 * Book 타입 스키마를 정확히 따르며, coverImage가 빈 문자열이면
 * BookCard에서 CSS 그라디언트 플레이스홀더를 렌더합니다.
 */

// 표지 플레이스홀더용 그라디언트 색상 세트
export const COVER_GRADIENTS = [
  "from-emerald-800 to-emerald-600",
  "from-blue-800 to-blue-500",
  "from-teal-700 to-cyan-500",
  "from-slate-700 to-slate-500",
  "from-green-700 to-lime-500",
  "from-indigo-700 to-purple-500",
  "from-rose-700 to-pink-500",
  "from-amber-700 to-yellow-500",
  "from-cyan-700 to-sky-500",
  "from-violet-700 to-fuchsia-500",
  "from-stone-700 to-stone-500",
  "from-orange-700 to-red-500",
  "from-emerald-600 to-teal-400",
];

export const newReleases: Book[] = [
  {
    id: "new-001",
    title: "내일의 침묵",
    author: "김현우",
    category: "소설",
    level: "초급",
    price: 16200,
    description: "현대 도시인의 고독과 소통을 다룬 장편소설. 침묵 속에서 피어나는 관계의 아름다움을 섬세하게 그려냅니다.",
    toc: ["프롤로그", "1부 침묵의 시작", "2부 소리 없는 대화", "3부 내일을 향해", "에필로그"],
    reviewSummary: "잔잔하지만 강렬한 여운을 남기는 소설. 현대인의 외로움에 공감하게 됩니다.",
    targetReader: "일상의 고독을 느끼는 20~40대 독자",
    pickupAvailable: true,
    coverImage: "",
  },
  {
    id: "new-002",
    title: "AI와 함께 걷는 법",
    author: "박지성",
    category: "과학",
    level: "입문",
    price: 22000,
    description: "인공지능 시대를 살아가는 현대인을 위한 실용 가이드. AI 기술의 원리부터 일상 활용법까지 쉽게 풀어냅니다.",
    toc: ["AI란 무엇인가", "일상 속 AI", "AI와 함께 일하기", "AI 시대의 미래", "부록"],
    reviewSummary: "비전공자도 이해할 수 있는 쉬운 AI 입문서. 실생활 예시가 풍부합니다.",
    targetReader: "AI에 관심 있는 비전공자, 직장인",
    pickupAvailable: true,
    coverImage: "",
  },
  {
    id: "new-003",
    title: "계절의 조각들",
    author: "이소라",
    category: "에세이",
    level: "입문",
    price: 14800,
    description: "사계절의 변화 속에서 발견하는 일상의 아름다움. 자연과 함께하는 삶의 이야기를 담은 에세이집.",
    toc: ["봄, 시작의 온도", "여름, 빛의 기록", "가을, 기억의 색", "겨울, 고요의 시간"],
    reviewSummary: "계절마다 한 번씩 꺼내 읽고 싶은 따뜻한 에세이. 자연 묘사가 아름답습니다.",
    targetReader: "자연과 일상에서 위로를 찾는 독자",
    pickupAvailable: false,
    coverImage: "",
  },
  {
    id: "new-004",
    title: "나의 일, 나의 항로",
    author: "최영호",
    category: "자기계발",
    level: "중급",
    price: 17500,
    description: "커리어 전환과 성장에 대한 실질적 조언. 10년차 직장인이 들려주는 일과 삶의 방향 찾기.",
    toc: ["왜 지금인가", "나만의 항로 설계", "전환의 기술", "성장의 습관", "다음 10년"],
    reviewSummary: "막연한 불안 대신 구체적인 액션 플랜을 얻을 수 있어 좋았습니다.",
    targetReader: "커리어 전환을 고민하는 30~40대 직장인",
    pickupAvailable: true,
    coverImage: "",
  },
  {
    id: "new-005",
    title: "기록의 기쁨",
    author: "정다운",
    category: "에세이",
    level: "입문",
    price: 15000,
    description: "글쓰기와 기록의 힘에 대한 에세이. 일기, 독서록, 메모 등 다양한 기록 방법과 그 기쁨을 나눕니다.",
    toc: ["기록을 시작하다", "하루 한 줄의 힘", "읽고 쓰는 습관", "기록이 만든 변화", "나만의 기록법"],
    reviewSummary: "기록 습관을 시작하고 싶은 사람에게 동기부여가 되는 책.",
    targetReader: "글쓰기와 기록에 관심 있는 모든 독자",
    pickupAvailable: true,
    coverImage: "",
  },
];

export const bestsellers: Book[] = [
  {
    id: "best-001",
    title: "트렌드 코리아 2026",
    author: "김난도 외",
    category: "경제경영",
    level: "중급",
    price: 18000,
    description: "2026년 대한민국 소비 트렌드를 예측하는 연간 베스트셀러. 10대 키워드로 미래 시장을 읽습니다.",
    toc: ["2026 트렌드 총론", "키워드 1~5", "키워드 6~10", "산업별 전망", "부록"],
    reviewSummary: "매년 기대하는 시리즈. 마케터, 기획자에게 필수 도서.",
    targetReader: "마케터, 기획자, 경영인, 트렌드에 관심 있는 일반 독자",
    pickupAvailable: true,
    coverImage: "",
  },
  {
    id: "best-002",
    title: "마흔에 읽는 쇼펜하우어",
    author: "강용수",
    category: "인문학",
    level: "중급",
    price: 15300,
    description: "중년의 문턱에서 만나는 쇼펜하우어의 철학. 인생 후반의 지혜를 담은 인문학 에세이.",
    toc: ["왜 마흔에 쇼펜하우어인가", "의지와 표상의 세계", "고독의 즐거움", "인생의 지혜", "마흔 이후의 삶"],
    reviewSummary: "어렵기만 했던 철학을 삶에 녹여낸 좋은 해설서.",
    targetReader: "인생의 전환점에 서 있는 30~50대 독자",
    pickupAvailable: true,
    coverImage: "",
  },
  {
    id: "best-003",
    title: "생성형 AI로 하는 일들",
    author: "오픈AI 연구팀",
    category: "과학",
    level: "초급",
    price: 24300,
    description: "ChatGPT부터 이미지 생성까지, 생성형 AI의 실전 활용법을 총망라한 가이드북.",
    toc: ["생성형 AI 개론", "텍스트 AI 활용", "이미지/영상 AI", "비즈니스 적용", "윤리와 미래"],
    reviewSummary: "실무에서 바로 쓸 수 있는 프롬프트와 팁이 가득. AI 입문자에게 추천.",
    targetReader: "AI를 실무에 활용하고 싶은 직장인, 크리에이터",
    pickupAvailable: false,
    coverImage: "",
  },
  {
    id: "best-004",
    title: "도시의 인문학",
    author: "박진영",
    category: "인문학",
    level: "중급",
    price: 19800,
    description: "서울, 도쿄, 파리, 뉴욕… 도시의 역사와 문화를 인문학적 시선으로 풀어낸 교양서.",
    toc: ["도시란 무엇인가", "서울의 기억", "도쿄의 질서", "파리의 예술", "뉴욕의 자유", "미래의 도시"],
    reviewSummary: "여행 에세이와 인문학의 만남. 도시를 보는 눈이 달라집니다.",
    targetReader: "여행과 도시 문화에 관심 있는 교양 독자",
    pickupAvailable: true,
    coverImage: "",
  },
];

export const recommendations: Book[] = [
  {
    id: "rec-001",
    title: "꾸준함의 기술",
    author: "한승민",
    category: "자기계발",
    level: "입문",
    price: 16500,
    description: "어떻게 습관을 만들고 유지할 것인가에 대한 깊은 고찰. 심리학과 뇌과학을 바탕으로 지속 가능한 변화를 제안합니다.",
    toc: ["습관의 과학", "시작의 기술", "지속의 비밀", "실패와 회복", "꾸준함의 열매"],
    reviewSummary: "작은 습관의 힘을 체감할 수 있는 실용서. 구체적인 실천법이 도움됩니다.",
    targetReader: "새로운 습관을 만들고 싶은 모든 독자",
    pickupAvailable: true,
    coverImage: "",
  },
  {
    id: "rec-002",
    title: "읽기의 역사",
    author: "서정우",
    category: "인문학",
    level: "중급",
    price: 21000,
    description: "인류가 정보를 처리해온 방식에 대한 철학적 탐구. 구전에서 디지털까지, 읽기의 진화를 추적합니다.",
    toc: ["구전의 시대", "문자의 탄생", "인쇄 혁명", "디지털 읽기", "읽기의 미래"],
    reviewSummary: "독서의 의미를 다시 생각하게 하는 깊이 있는 인문서.",
    targetReader: "독서와 지식 문화에 관심 있는 인문학 애호가",
    pickupAvailable: false,
    coverImage: "",
  },
  {
    id: "rec-003",
    title: "데이터 비즈니스",
    author: "윤지혜",
    category: "경제경영",
    level: "중급",
    price: 23000,
    description: "데이터가 어떻게 가치를 창출하고 시장을 변화시키는가. 데이터 경제의 핵심을 비즈니스 관점에서 분석합니다.",
    toc: ["데이터 경제란", "가치 창출 모델", "플랫폼과 데이터", "개인정보와 규제", "미래 비즈니스"],
    reviewSummary: "데이터 비즈니스의 전체 그림을 잘 잡아주는 경영서.",
    targetReader: "데이터 산업과 비즈니스 전략에 관심 있는 기획자, 경영인",
    pickupAvailable: true,
    coverImage: "",
  },
  {
    id: "rec-004",
    title: "숲의 기억",
    author: "장은채",
    category: "소설",
    level: "초급",
    price: 15800,
    description: "잃어버린 시간을 찾아 떠나는 한 남자의 신비로운 여정. 숲이라는 공간이 기억과 치유의 매개가 되는 판타지 소설.",
    toc: ["숲으로의 초대", "기억의 나무", "시간의 강", "잃어버린 것들", "돌아가는 길"],
    reviewSummary: "몽환적인 분위기와 아름다운 문장이 인상적인 소설.",
    targetReader: "판타지와 치유 서사를 좋아하는 소설 독자",
    pickupAvailable: true,
    coverImage: "",
  },
];

/** 전체 도서 목록 (나중에 JSON 데이터로 교체) */
export const allBooks: Book[] = [...newReleases, ...bestsellers, ...recommendations];
