import { Book } from "@/types/book";

/**
 * 더미 도서 데이터 — 나중에 실제 샘플 JSON으로 교체합니다.
 * Book 타입 스키마를 정확히 따르며, coverImage가 빈 문자열이면
 * BookCard에서 CSS 그라디언트 플레이스홀더를 렌더합니다.
 */

// 표지 플레이스홀더용 그라디언트 색상 세트
export const COVER_GRADIENTS = [
  "from-emerald-800 to-emerald-600",
  "from-blue-800 to-blue-500",
  "from-teal-700 to-cyan-500",
  "from-slate-700 to-slate-500",
  "from-green-700 to-lime-500",
  "from-indigo-700 to-purple-500",
  "from-rose-700 to-pink-500",
  "from-amber-700 to-yellow-500",
  "from-cyan-700 to-sky-500",
  "from-violet-700 to-fuchsia-500",
  "from-stone-700 to-stone-500",
  "from-orange-700 to-red-500",
  "from-emerald-600 to-teal-400",
];

export const newReleases: Book[] = [
  {
    id: "new-001",
    title: "내일의 침묵",
    author: "김현우",
    category: "소설",
    level: "초급",
    price: 16200,
    description: "현대 도시인의 고독과 소통을 다룬 장편소설. 침묵 속에서 피어나는 관계의 아름다움을 섬세하게 그려냅니다.",
    toc: ["프롤로그", "1부 침묵의 시작", "2부 소리 없는 대화", "3부 내일을 향해", "에필로그"],
    reviewSummary: "잔잔하지만 강렬한 여운을 남기는 소설. 현대인의 외로움에 공감하게 됩니다.",
    targetReader: "일상의 고독을 느끼는 20~40대 독자",
    pickupAvailable: true,
    coverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuA_Po0gmzwfS3APDCn0-KGEDc-DtfTfhN5d1LfTvicTduIDzYXAQ2iVGBrGxfQrUWv2Q0QMW2P4jT8kol5t1d-hMlDGST255VlPDv1X0QdfsOEzxatD7DhvQ-xokyJFPmJFPan_ZI0c6NOA1mz0L3W2BMszCG1V9tXHsRorwtCvm0Qc5fyJNWe36VUN7hmD95tx0ZmkcEd5lakp9uTonSq3Ap6KyWFiZx1fQ9UwovlVkYXmtAw50GLUr4F3a_qgki-PcOOLnP1GasM",
  },
  {
    id: "new-002",
    title: "AI와 함께 걷는 법",
    author: "박지성",
    category: "과학",
    level: "입문",
    price: 22000,
    description: "인공지능 시대를 살아가는 현대인을 위한 실용 가이드. AI 기술의 원리부터 일상 활용법까지 쉽게 풀어냅니다.",
    toc: ["AI란 무엇인가", "일상 속 AI", "AI와 함께 일하기", "AI 시대의 미래", "부록"],
    reviewSummary: "비전공자도 이해할 수 있는 쉬운 AI 입문서. 실생활 예시가 풍부합니다.",
    targetReader: "AI에 관심 있는 비전공자, 직장인",
    pickupAvailable: true,
    coverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuBzFyFBPaq3EiW0uXnNpaL30AisC1pZR1ZnyQ3qd7L6-NK_UcD-13VmRfTqutxa40q9_3eS5iSbqOzSqOs0uphLXUx4Y_kZK2YUl0lAWOzAbx0GMhBA8m_Ab6B9PRjfAC8Pn4VOuaL3VEqQ2r0_Mno3aQv0l3ce9KgFiBRnyjcfMkBu_9TKRPkIh1W8tgkCUTF30NL9Sx30Nl2JsGbWSTstFY-WxYK-EMatdtFpKK9ryHuCQHwesWgoMcslvHEZCnhg5wnLX609LJg",
  },
  {
    id: "new-003",
    title: "계절의 조각들",
    author: "이소라",
    category: "에세이",
    level: "입문",
    price: 14800,
    description: "사계절의 변화 속에서 발견하는 일상의 아름다움. 자연과 함께하는 삶의 이야기를 담은 에세이집.",
    toc: ["봄, 시작의 온도", "여름, 빛의 기록", "가을, 기억의 색", "겨울, 고요의 시간"],
    reviewSummary: "계절마다 한 번씩 꺼내 읽고 싶은 따뜻한 에세이. 자연 묘사가 아름답습니다.",
    targetReader: "자연과 일상에서 위로를 찾는 독자",
    pickupAvailable: false,
    coverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuAiGNCeb4bETXoSL16DKhcZZbz2t25cEXTI6PnLHeffpsmoQDaZgGDHwl2lS51FyIFgS1GFOqZqmoRVBPVeRNN9C7wQQjf-An_MuQsg24sG1HiRE1s2fEzeMdMUw5qJBwJcQsuz6MEEiEKqNoGo3oQ6JiZYxIu36Q0dMAIkH6j3vy8KQArUzhCCm5MhcpYO3GbGUabBzfJy9BlTGr4PavcMwMAK7jU_3fUkOsa67ke8rESck35Wxl6qFLkj6VdgY91Xmw3_1t-PoW8",
  },
  {
    id: "new-004",
    title: "나의 일, 나의 항로",
    author: "최영호",
    category: "자기계발",
    level: "중급",
    price: 17500,
    description: "커리어 전환과 성장에 대한 실질적 조언. 10년차 직장인이 들려주는 일과 삶의 방향 찾기.",
    toc: ["왜 지금인가", "나만의 항로 설계", "전환의 기술", "성장의 습관", "다음 10년"],
    reviewSummary: "막연한 불안 대신 구체적인 액션 플랜을 얻을 수 있어 좋았습니다.",
    targetReader: "커리어 전환을 고민하는 30~40대 직장인",
    pickupAvailable: true,
    coverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuBiVbO4L7mZR4uGnborrpR6VR0Xq2Hxiwkgz5hvHcl1qq-uf7gmdQhoe_uN0O0rk5F2pnRcyrANfNWKDaIVWJQ0i_P09-Vu-hX9xR2M8xYUi5SAPT1RWFfrXGvuP2cI7LEempM7LTUiSJgbSKiP1gxPi-rgTdPE3n074gVrf2C-RefAa-ar8BwkPzN8dhYZYONwWpG1TVh-Trljn_suCmeF7VTs7oWc47S_XLMtg-NU30EgFO6SOOrEcltncRTULLztGE2meVSpLQU",
  },
  {
    id: "new-005",
    title: "기록의 기쁨",
    author: "정다운",
    category: "에세이",
    level: "입문",
    price: 15000,
    description: "글쓰기와 기록의 힘에 대한 에세이. 일기, 독서록, 메모 등 다양한 기록 방법과 그 기쁨을 나눕니다.",
    toc: ["기록을 시작하다", "하루 한 줄의 힘", "읽고 쓰는 습관", "기록이 만든 변화", "나만의 기록법"],
    reviewSummary: "기록 습관을 시작하고 싶은 사람에게 동기부여가 되는 책.",
    targetReader: "글쓰기와 기록에 관심 있는 모든 독자",
    pickupAvailable: true,
    coverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuBKVPbO7lBfmpQ2Kz30gZr2bKshiz3s08P-Hu2QtY9dtT2xihvkGXBqPq-nBZhYsmrVjwGxp3AvEZtp4XaIU4bM5ax_rmoU4hJROUOQSKYoW45scxVMIzR85sVt2w-GJbCe2oEGI9fQK9_KypueA9FsNeKES-Nl_q-setUHOAfcaF0QORUCgMEpE8OWMi1NN3DmiZo8nWgSBFPTYVvlu0FdVkUMd2Y-pbGacD4dMjFj7wTqYyDDeWSFxxiwXbf_JC2HEaJsC9Ccxbk",
  }
];

export const bestsellers: Book[] = [
  {
    id: "best-001",
    title: "트렌드 코리아 2026",
    author: "김난도 외",
    category: "경제경영",
    level: "중급",
    price: 18000,
    description: "2026년 대한민국 소비 트렌드를 예측하는 연간 베스트셀러. 10대 키워드로 미래 시장을 읽습니다.",
    toc: ["2026 트렌드 총론", "키워드 1~5", "키워드 6~10", "산업별 전망", "부록"],
    reviewSummary: "매년 기대하는 시리즈. 마케터, 기획자에게 필수 도서.",
    targetReader: "마케터, 기획자, 경영인, 트렌드에 관심 있는 일반 독자",
    pickupAvailable: true,
    coverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuB2Uq_qirO7ILf8kWUshtc3-qKgrd2cfSwmbkxp7cV9GO2j_bTlZLMuv6zMy3F3QXTn1B-GWOGBCFmVeKgRWuAvpMcJ2lMYglkrJXNlPkXtI8ZF25r9m-y5kiIjqoieyQqLpNO-L-b91746bNr70Fz-28SH-5gmSRVn31JWIhV2zDLHriQCDNQOswTzMKIgevWh-LxdL8Gtri-5at-41nLMj6V5u_oSrepB2eO7x516Wv9IIP4Twboc8REhebM6QZ3-4lBmoJc1oKQ",
  },
  {
    id: "best-002",
    title: "마흔에 읽는 쇼펜하우어",
    author: "강용수",
    category: "인문학",
    level: "중급",
    price: 15300,
    description: "중년의 문턱에서 만나는 쇼펜하우어의 철학. 인생 후반의 지혜를 담은 인문학 에세이.",
    toc: ["왜 마흔에 쇼펜하우어인가", "의지와 표상의 세계", "고독의 즐거움", "인생의 지혜", "마흔 이후의 삶"],
    reviewSummary: "어렵기만 했던 철학을 삶에 녹여낸 좋은 해설서.",
    targetReader: "인생의 전환점에 서 있는 30~50대 독자",
    pickupAvailable: true,
    coverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuC-BCtpmF1zOv5FXDihLmppI5v3Z2efPqc8I7rRKPxkeN-AZEisMkqgUTAZZhRUV4XUgSdLd24S_n-PpehvmfFBlv9VK93H9gfPAfvBvUCD3YHi1VNbYou3CC3gRwC9zA0P6moQrpEu3gFjZq3WEEngvaT-sM0tvQjxVNUnDo9xfOG4JY0VYwoBBK7DGNhGzhVsdUI-5RUZodinadggyHGn3nU1ANA5ABvouRfe-qCJGiP4zTypAhYaSSBgSh_sWLe6zDynNfMamsE",
  },
  {
    id: "best-003",
    title: "생성형 AI로 하는 일들",
    author: "오픈AI 연구팀",
    category: "과학",
    level: "초급",
    price: 24300,
    description: "ChatGPT부터 이미지 생성까지, 생성형 AI의 실전 활용법을 총망라한 가이드북.",
    toc: ["생성형 AI 개론", "텍스트 AI 활용", "이미지/영상 AI", "비즈니스 적용", "윤리와 미래"],
    reviewSummary: "실무에서 바로 쓸 수 있는 프롬프트와 팁이 가득. AI 입문자에게 추천.",
    targetReader: "AI를 실무에 활용하고 싶은 직장인, 크리에이터",
    pickupAvailable: false,
    coverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuA6mTwqZAUAOr8IASbSDc3wb6Jv9KzNa1Hqixcdq603eFn6DZ50_ffSANfkxc1uSWepZX1V3dp79MNuDSovtVbP7lZD6zc75z3pSouk3Gpj2Fr-pMw3vGRrIjs96eXIvJcpWj_A-ar01xtzinqLeVaykkf801fd6dDE8iZvmKqlZWL7tpW_V_NVHeyVJj1ap4pN_m50J1OzXwg7UUg1fR0noy69ze1xb_4yrv5DUaIIWTCW1Txpi23UYe6w9II1AwGKHN_USusUGhs",
  },
  {
    id: "best-004",
    title: "도시의 인문학",
    author: "박진영",
    category: "인문학",
    level: "중급",
    price: 19800,
    description: "서울, 도쿄, 파리, 뉴욕… 도시의 역사와 문화를 인문학적 시선으로 풀어낸 교양서.",
    toc: ["도시란 무엇인가", "서울의 기억", "도쿄의 질서", "파리의 예술", "뉴욕의 자유", "미래의 도시"],
    reviewSummary: "여행 에세이와 인문학의 만남. 도시를 보는 눈이 달라집니다.",
    targetReader: "여행과 도시 문화에 관심 있는 교양 독자",
    pickupAvailable: true,
    coverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuDwRVTHt9LIBf9EaMy-FDv9df2hvlVsIai1fvZc2BPlHMvxvQ43rOslZtTiL9jT_eDDL6j7vTc_rJH2NMusBojxk7CDxvlpNeFia1DQTVzaprvthq1H278ZHZY8OnfZ80JCN4HGIXeWbxN18owU5KCDzJGSko58Bb77859lwaFj4MUzgv4_4EUaVEBG81qY7WKkgJBh9x4Aeeq56dWD6lTkHEGeoHPE-emyG7m-pyF0E4ghV27ECOmeFDphWx2s_XPtCdXhkcb9bNI",
  }
];

export const recommendations: Book[] = [
  {
    id: "rec-001",
    title: "꾸준함의 기술",
    author: "한승민",
    category: "자기계발",
    level: "입문",
    price: 16500,
    description: "어떻게 습관을 만들고 유지할 것인가에 대한 깊은 고찰. 심리학과 뇌과학을 바탕으로 지속 가능한 변화를 제안합니다.",
    toc: ["습관의 과학", "시작의 기술", "지속의 비밀", "실패와 회복", "꾸준함의 열매"],
    reviewSummary: "작은 습관의 힘을 체감할 수 있는 실용서. 구체적인 실천법이 도움됩니다.",
    targetReader: "새로운 습관을 만들고 싶은 모든 독자",
    pickupAvailable: true,
    coverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuDsIAUMwD-qpC9YfKuQ-8amJiJ5sPp4M_7n0SAlNuVlqf0tQvBrdbgAKPDRv5MIm6btKFgdo9AwSjEHJ-s-Gvf1KnHQ2KBpv6N0gppPnU6BnfSZ_Sc9De6oNuDC51fEgdWdOq2LWLIg13v-Sm2SYU54-KiPl-ZVe9aY5P_PwgGhIYEXlmDCXebEdFWPcEIwCGKTK-XmN2XM703NwPeRZgqOwyj5svI3gvZixov8G6Nbdsg86vXAcUMkwfgiz3XOO6EklJKGdbcQxCU",
  },
  {
    id: "rec-002",
    title: "읽기의 역사",
    author: "서정우",
    category: "인문학",
    level: "중급",
    price: 21000,
    description: "인류가 정보를 처리해온 방식에 대한 철학적 탐구. 구전에서 디지털까지, 읽기의 진화를 추적합니다.",
    toc: ["구전의 시대", "문자의 탄생", "인쇄 혁명", "디지털 읽기", "읽기의 미래"],
    reviewSummary: "독서의 의미를 다시 생각하게 하는 깊이 있는 인문서.",
    targetReader: "독서와 지식 문화에 관심 있는 인문학 애호가",
    pickupAvailable: false,
    coverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuAbr7Z-yD7MZqpp1-W5jb4mrI4F3wjSCHFyxVMB5vcc5XG2SUf0MAuVh8MRywLqttfVM8uYbLPtWaJDsDtKcvlsRuF-IKYJeQnKLvj5mJ3q8Z5QKFTNR8-1gEym7QWudH_-HmYnQMDqAn1sdvH4xzUE7FU56n-hq7dBwsltDc86xDeluw9cmTv-vOnA48K--84K7uQIhUMXt4gP17-A-_P10a5V4wEpfjx5nyHslUsVA6bSY39C-5PWRLHu8GwhkbBLu8v890FijaI",
  },
  {
    id: "rec-003",
    title: "데이터 비즈니스",
    author: "윤지혜",
    category: "경제경영",
    level: "중급",
    price: 23000,
    description: "데이터가 어떻게 가치를 창출하고 시장을 변화시키는가. 데이터 경제의 핵심을 비즈니스 관점에서 분석합니다.",
    toc: ["데이터 경제란", "가치 창출 모델", "플랫폼과 데이터", "개인정보와 규제", "미래 비즈니스"],
    reviewSummary: "데이터 비즈니스의 전체 그림을 잘 잡아주는 경영서.",
    targetReader: "데이터 산업 and 비즈니스 전략에 관심 있는 기획자, 경영인",
    pickupAvailable: true,
    coverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuDGXOYjHh9vDLO3ElXkCx6V67Ka8PDthKEwN3Dl8tUjiaiVIFmJoZ1YpJks30zQkfJ6MfWpZ5J7xpO_bOY793AsiyBSnRCUX7SBswpBvVf5iTVk0VoBdRKanGlKocQczopNY_kJj7gM2DDytaQ5O4OEPx_cNgtglfjCS3TpAtnCo2dAC4cE3eG1zUn4Llwfx16vpUNK11Gx-AFvlBfKZkv4_4klFt7YNLQvojQXstFoIgZlEpqp81j2mntk1aD9ez8OQzhSrHot1lQ",
  },
  {
    id: "rec-004",
    title: "숲의 기억",
    author: "장은채",
    category: "소설",
    level: "초급",
    price: 15800,
    description: "잃어버린 시간을 찾아 떠나는 한 남자의 신비로운 여정. 숲이라는 공간이 기억과 치유의 매개가 되는 판타지 소설.",
    toc: ["숲으로의 초대", "기억의 나무", "시간의 강", "잃어버린 것들", "돌아가는 길"],
    reviewSummary: "몽환적인 분위기와 아름다운 문장이 인상적인 소설.",
    targetReader: "판타지와 치유 서사를 좋아하는 소설 독자",
    pickupAvailable: true,
    coverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuDf6phJODFxv_hJOPUVe1AklMzAxeSL2VN-j9gsviWTSc5uai-ATrGnlIJRcBM76-xIL3GUXbjoZxFkWJt4fUs1O1lB07A2NzSlEBrvBR1uli5wEP59PC1_UgOWu1iKtgUFLL0-DT5vXpjWS6bQeTIecln1_p2O5yuG1d-w-9v5GAawkkHyX0NQLbetvquQFt3WKOfgaiAXzIOCMxNOMr6WsyuKcZzcaJlxh4o-lzrpj77udXtMH3H8GeFNp7OBwzhCN73-4O_loZg",
  }
];

/** 전체 도서 목록 (나중에 JSON 데이터로 교체) */
export const allBooks: Book[] = [...newReleases, ...bestsellers, ...recommendations];
